apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "javasp.labels" . | nindent 4 }}
  name: {{ template "javasp.fullname" . }}-config
data:
  application.yaml: |
  {{- if .Values.configOverride -}}
  {{- .Values.configOverride | nindent 4 }}
  {{- else -}}
  {{- .Files.Get "files/application.yaml" | nindent 4 }}
  {{ end }}
