apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "collibra-data-catalog-plugin"
          valueMap:
            COLLIBRA_USERNAME: user
            COLLIBRA_PASSWORD: pass
