spring:
  application:
    name: collibra-data-catalog-plugin

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /docs

logging:
  level:
    it.agilelab.witboost.datacatalogplugin: DEBUG
    org.zalando.logbook: TRACE

collibra:
  communityId: ""
  dataProductTypeId: ""
  statusId: ""
  domainTypeId: ""
  descriptionAttributeTypeId: ""
  columnTypeId: ""
  relationTypeId: ""
  businessTermTypeId: ""

api:
  username: ${COLLIBRA_USERNAME}
  password: ${COLLIBRA_PASSWORD}
  endpoint: ${COLLIBRA_HOST}

custom-url-picker:
  cors:
    endpointMask: "/v1/resources/**"
    origin: ""